### ISSUE TITLE
Problem with binding parameters in @Query

### ISSUE THREAD

**Issue by cmoine** [arangodb/spring-data#122]
At first I wrote:
```
	@Query("FOR p IN participant FILTER p.visibility == 'PUBLIC' && p.type == 'ORGANIZATION' && (like(p.nom, @0, true) || like(p.description, @0, true) || like(p.tags, @0, true)) SORT p.nom ASC RETURN p")
	public Iterable<Participant> search(String query);
```
It works perfectly when I run it from Eclipse, but for some reasons I didn't undestand deeply yet, when I run it from gradle, I obtain:
> com.arangodb.ArangoDBException: Response: 400, Error: 1551 - AQL: no value specified for declared bind parameter '0' (while parsing)
I debug the problem, and I ended up in StringBasedArangoQuery.extractBindVars (v3.1.0):
In one case, the "param.isNamedParameter()" is true, and it is false in the otehr execution mode :-(

I ended up with this workaround:
`public Iterable<Participant> search(@Param("0") String query);`
It seems that the arango engine only recognize @0 parameters, so I forced it with the @Param("0") (only an assumption)

I have stopped my research, but if you need more information, I am your man :-)

**Comment by christian-lechner** [comment]
Hello @cmoine 

Spring does the following to find out the name of a parameter:
- Check if there is an explicit `@Param` annotation present, if yes, use this value, otherwise
- Try to load the name from the class file via reflection (your sources must be compiled with the `-parameters` flag), if successful, use this value, otherwise
- Use the index of the parameter as name

This means that the class files that are compiled by your Eclipse do not include parameter names and the files that are compiled by your Gradle script do contain them.

You can either add the `-parameters` flag in your Eclipse compiler config or make sure Gradle doesn't include it.

**Comment by cmoine** [comment]
Thank you @christian-lechner , it fixed my problem, that is great thanks a lot !

Simply had to check "Store information about method parameters" in Eclipse Preferences -> Java Compiler :)
