### ISSUE TITLE
Document id missing collection name?

### ISSUE THREAD

**Issue by lotabout** [arangodb/spring-data#124]
An example from [spring data demo](https://github.com/arangodb/spring-data-demo):

```
Ned Stark saved in the database with id: 'characters/259672'
Found Character [id=characters/259672, name=Ned, surname=Stark, alive=true, age=41]
```

The retrieved document's id is `characters/259672` which includes the collection name `characters`. When I try this at home the collection name is missing, the id contains only the `259672` part.

`repository.findById(doc.getId())` works as expected but the custom queries won't. For example:

```
    @Query("FOR v IN 0..@distance " +
            "ANY @id relations " +
            "RETURN distinct v")
    Set<Customer> getNeighbours(@Param("id") String id, @Param("distance") int distance);
```

And `getNeighbour(doc.getId(), 0)` will fail. I have to fire `getNeighbour("customer/" + doc.getId(), 0)` manually.

Is this expected?

- ArangoDB version: 3.3.14
- arangodb-spring-data version: 3.1.1

**Comment by mpv1989** [comment]
The behavior of the annotation `@Id` changed in arangodb-spring-data version 3.0.0. It now only contains the document `_key` and not the `_id`.

From the [Changelog](https://github.com/arangodb/spring-data/blob/master/ChangeLog.md#changed-1)
> save `@Id` values as `_key` instead of `_id`

As you already mentioned, `findById` still works. But when you want to perform a custom query and you need the `_id` field instead of `_key` - which is the case when performing a graph query - you have to work with the annotation `@ArangoId` on a String field in your bean, which gives you the `_id` of the document. Also descriped in the [migration docs](https://github.com/arangodb/spring-data/blob/master/docs/Drivers/SpringData/Migration/Migrating-2.x-3.0.md).

**Comment by lotabout** [comment]
@mpv1989 Thanks! `@ArangoId` works like a charm!

Maybe it's better to update the demo and doc. Somehow it is hard to find such information. :)
