### ISSUE TITLE
Validate existent documents on insert edge

### ISSUE THREAD

**Issue by yguad** [arangodb/spring-data#136]
When I insert a document with type edge, if I don't send the whole object referenced in _from and in _to it has a strange behavior. It would very good the possibility of to send only identifiers.
Is it possible to send the vertx references (identifier, for example "collection/1234")  in the _from and _to fields and validate spring-data if they exist before inserting them?

**Comment by Simran-B** [comment]
>  it has a strange behavior

Can you please the describe the behavior?

**Comment by mpv1989** [comment]
> Is it possible to send the vertx references (identifier, for example "collection/1234") in the _from and _to fields and validate spring-data if they exist before inserting them?

Validating of edges in ArangoDB is only possible through _named graphs_ and the corresponding [graph REST API](https://docs.arangodb.com/3.3/HTTP/Gharial/), which is currently not supported by Spring Data ArangoDB. There is an open [feature request](https://github.com/arangodb/spring-data/issues/76) for that but no ETA.

**Comment by yguad** [comment]
ArangoDB spring-data allows me insert edges when the _from or _to referenced documents doesn't exists. 
Thanks @mpv1989 for your reply. I would not like it use rest api. I found a way to implement using directly the arangodb driver but it would be interesting to configure it using spring data.

**Comment by rashtao** [comment]
Since ArangoDB graphs API does not support overwriting (https://www.arangodb.com/docs/stable/http/gharial-edges.html#create-an-edge), it is not suitable for implementing `save` method in `ArangoRepository`, which requires insert/replace behavior.
Therefore for the moment, support to named graphs API can only be implemented in the `ArangoTemplate` API.

Closing for now, please refer to #76 for further discussion.
