### ISSUE TITLE
Can't retrieve Edge documents as an attribute

### ISSUE THREAD

**Issue by dmartinpro** [arangodb/spring-data#15]
I'm trying to implement one of the documentation example:
```
@Document("persons")
public class Person {
  @From
  private List<Relation> relations;
}

@Edge(name="relations")
public class Relation {
  ...
}
```

But I'm unable to get a list of relations as expected.

First issue: @Edge doesn't have a "name" attribute (it's "value").

But it's not clear what Relation class should have as attributes.
Do I have to add a from and to attribute? Should I add the @From and @To annotations on them?

What I want doesn't seem complicated:
- 2 different types of Document, let's call them A and B
- an Edge document with some attributes describing the relation, let's call it Link
- Be able to get an A instance, which has a collection of Links, where each Link can point to the B instance.
That way, I'm able to get all Links attributes and related Documents.

**Comment by mpv1989** [comment]
Hi @dmartinpro,

First issue: Yes, your are right. The docs are wrong it has to be `value`.

Let me quickly write down your needed classes for your case:

Class `A` with a field annotated with `@Id` and the list of links annotated with `@From` (or `@To` depending on the direction of you edge). I highly suggest to set the param `lazy` to `true` otherwise you can easily run into infinity loops.
```Java
@Document
public class A {
  @Id private String id;
  @From(lazy = true) private List<Link> links;

  public A() {
    super();
  }
  public String getId() {
    return id;
  }
  public List<Link> getLinks() {
    return links;
  }
}
```
Class `B` only needs a field annotated with `@Id`.
```Java
@Document
public class B {
  @Id private String id;

  public B() {
    super();
  }
  public String getId() {
    return id;
  }
}
```

Class `Link` has to be annotated with `@Edge` and needs a field from type `A` annotated with `@From` and a field from type `B` annotated with `@To`. I also recommend here using `lazy`=`true`.
```Java
@Edge
public class Link {
  @Id private String id;
  @From(lazy = true) private final A a;
  @To(lazy = true) private final B b;

  public Link(final A a, final B b) {
    super();
    this.a = a;
    this.b = b;
  }
  public String getId() {
    return id;
  }
  public A getA() {
    return a;
  }
  public B getB() {
    return b;
  }
}
```

Usage (i.e. with `ArangoOperations`):
```Java
@Autowired
private ArangoOperations operations;

...

A a = new A();
operations.insert(a);

B b = new B();
operations.insert(b);

operations.insert(new Link(a, b));

Optional<A> find = operations.find(a.getId(), A.class);
find.ifPresent(e -> {
  e.getLinks();
  ...
});
```
