### ISSUE TITLE
direct operations on database not reflected on ArangoContext

### ISSUE THREAD

**Issue by arking7** [arangodb/spring-data#206]
How to reproduce: Start spring data arango, go to database web ui and delete collection "X" from ui, then call to collection("X").truncate() will raise an error.

ArangoContext not reflexing the change on database, thus collection("X") not returning null, and no new collection is created automatically.

Expected behavior: Arango detects the change, and create a new collection named "X" automatically so subsequently call to truncate() will success.

**Comment by rashtao** [comment]
There is already an ongoing discussion about collections creation on startup: 
https://github.com/arangodb/spring-data/issues/125

The main idea is to optionally create collections and indexes once for all at startup. 
So in order to address your needs, I would suggest you implementing such checks in your code, in case using the underlying Java driver directly, eg.:

```Java
var collection = template.driver().db(DB).collection(C);
if(!collection.exists())
  collection.create();
collection.truncate();
```

**Comment by arking7** [comment]
Thanks, that does work. However my scenario is a bit different, I deleted the database during runtime, so creating collection at startup does not seem like an option for me.

I hope there is an option to invalid the cache on the template level.

**Comment by rashtao** [comment]
I am afraid this is quite an unusual use case that is not addressed by Spring Data.
I would suggest you dealing with it catching the ArangoExceptions related to database/collection not found and recreating db, collections and indexes in such cases.

**Comment by rashtao** [comment]
Closing for now, please reopen if still relevant.
